/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author pedro
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SettingsWindow = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SimulationWindow = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ResultsWindow = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        StadisticsWindow = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Bienvenido a SOmulation");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel2.setText("Configuración");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 80, 30));

        SettingsWindow.setText("Configuracion");
        SettingsWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsWindowActionPerformed(evt);
            }
        });
        jPanel1.add(SettingsWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, 30));

        jLabel3.setText("Simulación");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 70, 30));

        SimulationWindow.setText("Simulation");
        SimulationWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimulationWindowActionPerformed(evt);
            }
        });
        jPanel1.add(SimulationWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 100, 30));

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel4.setText("Resultados");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 70, 30));

        ResultsWindow.setText("Resultados");
        ResultsWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultsWindowActionPerformed(evt);
            }
        });
        jPanel1.add(ResultsWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 100, 30));

        jLabel5.setText("Estadisticas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 70, 30));

        StadisticsWindow.setText("Estadisticas");
        StadisticsWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StadisticsWindowActionPerformed(evt);
            }
        });
        jPanel1.add(StadisticsWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, 30));

        jLabel6.setText("El campo de juego de los grandes");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void StadisticsWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StadisticsWindowActionPerformed
        // TODO add your handling code here:
        Stadistics trabucco = new Stadistics(this);
        this.setVisible(false);
        trabucco.setVisible(true);
    }//GEN-LAST:event_StadisticsWindowActionPerformed

    private void SettingsWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsWindowActionPerformed
        // TODO add your handling code here:
        Settings c = new Settings(this);
        this.setVisible(false);
        c.setVisible(true);
    }//GEN-LAST:event_SettingsWindowActionPerformed

    private void SimulationWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimulationWindowActionPerformed
        // TODO add your handling code here:
        Simulation Quintero = new Simulation(this);
        this.setVisible(false);
        Quintero.setVisible(true);
    }//GEN-LAST:event_SimulationWindowActionPerformed

    private void ResultsWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultsWindowActionPerformed
        // TODO add your handling code here:
        Results David = new Results(this);
        this.setVisible(false);
        David.setVisible(true);
    }//GEN-LAST:event_ResultsWindowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResultsWindow;
    private javax.swing.JButton SettingsWindow;
    private javax.swing.JButton SimulationWindow;
    private javax.swing.JButton StadisticsWindow;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
